include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    always_declare_return_types: error
    always_put_required_named_parameters_first: error
    #always_specify_types: warning
    avoid_empty_else: error
    avoid_init_to_null: error
    avoid_print: error
    await_only_futures: error
    camel_case_types: error
    prefer_final_fields: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_relative_imports: error
    prefer_single_quotes: error
    unnecessary_this: error
    use_key_in_widget_constructors: error
    avoid_unused_constructor_parameters: error
    prefer_const_constructors: error
    avoid_relative_lib_imports: error
    empty_constructor_bodies: error
    unnecessary_string_interpolations: error
    unnecessary_null_checks: error
    unused_import: error
    always_use_package_imports: error
    empty_catches: error
    dead_code: error
    prefer_const_declarations: error
    cancel_subscriptions: error
    no_duplicate_case_values: error
    curly_braces_in_flow_control_structures: true
    unnecessary_new: error
    unrelated_type_equality_checks: error
    use_build_context_synchronously: error
    prefer_null_aware_operators: error
    sized_box_for_whitespace: error
    sort_constructors_first: error
    use_named_constants: error
    constant_identifier_names: error

linter:

  rules:
    empty_catches: true
    always_use_package_imports: true
    avoid_empty_else: true
    prefer_const_declarations: true
    cancel_subscriptions: true
    no_duplicate_case_values: true
    curly_braces_in_flow_control_structures: true
    unnecessary_new: true
    avoid_print: true
    prefer_single_quotes: true
    prefer_final_fields: true
    always_declare_return_types: true
    await_only_futures: true
    avoid_types_as_parameter_names: true
    #always_specify_types: true
    prefer_const_constructors: true
    always_put_required_named_parameters_first: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: true
    camel_case_types: true
    empty_constructor_bodies: true
    prefer_null_aware_operators: true
    sized_box_for_whitespace: true
    sort_constructors_first: true
    use_named_constants: true
    constant_identifier_names: true
    prefer_is_empty: true
    prefer_is_not_empty: true
